### ISSUE TITLE
youtube.com/devicesupport

### ISSUE THREAD

**Issue by eaglejohn** [dharyk/jQuery.youtubeChannel#10]
All videos in the YouTube channel are showing an error and are pointing to this video:
https://www.youtube.com/watch?v=UKY3scPIMd8&feature=youtube_gdata_player
![screen shot 2015-05-06 at 20 52 35](https://cloud.githubusercontent.com/assets/985981/7501058/dba2a9bc-f431-11e4-803c-67f0d1ba813a.png)

**Comment by dharyk** [comment]
The api version used by this plugin has been deprecated about a year ago. This repository will be closed.
